export const PROJECT_CONFIG = {
    EPL_PROJECT_KEY: import.meta.env.EPL_PROJECT_KEY,
    EPL_PROJECT_DATABASE_KEY: import.meta.env.EPL_PROJECT_DATABASE_KEY,
};
export const API_CONFIG = {
    EPL_API_KEY: import.meta.env.EPL_API_KEY,
    EPL_API_TEAMS_PATH: import.meta.env.EPL_API_TEAMS_PATH,
    EPL_API_STANDINGS_PATH: import.meta.env.EPL_API_STANDINGS_PATH,
    EPL_API_MATCHES_PATH: import.meta.env.EPL_API_MATCHES_PATH,
};
export const COLLECTIONS_CONFIG = {
    EPL_PROJECT_TEAMS_COLLECTION: import.meta.env.EPL_PROJECT_TEAMS_COLLECTION,
    EPL_PROJECT_STANDINGS_COLLECTION: import.meta.env.EPL_PROJECT_STANDINGS_COLLECTION,
    EPL_PROJECT_MATCHES_COLLECTION: import.meta.env.EPL_PROJECT_MATCHES_COLLECTION,
};